setwd("/Users/xuebozhao/Documents/LuLab/wheatSpeciation/pca/ABlineage")
a = read.table("AAexontreeIN.eigenvec",head =T)
head(a[,1:4])
av = read.table("AAexontreeIN.eigenval",head =F)
explained_ratio = av[,1]/sum(av[,1])
pca_color = read.delim("/Users/xuebozhao/Documents/LuLab/wheatSpeciation/pca/treeRangeColor_E2.txt",head =F)
dim(a)
dim(pca_color)
index = match(pca_color$V1,a$IID)
head(explained_ratio)
#par(bg="black")
#par(mfrow=c(2,1), oma=c(4.5,4, 4, 2.5), mar=c(0.5,1,0.5,1), cex=1)
#layout(matrix(c(1:2), 1, 2, byrow = F), widths=rep(1,2), heights=c(rep(1,2),0.05))
#bty="l" 只保留左和下两条边框
plot(a[index,3:4],xlab="PC1 (42.01%)",ylab="PC2 (13.70%)",cex.lab=1.5,mgp=c(2.5,1,0),cex.axis=1,col= as.character(pca_color[,3]),pch=19,bg="transparent",cex=1.5)

#####
rm(list=ls())
library(shape)
library(cluster)
library(geosphere)
library(RColorBrewer)
display.brewer.all()
brewer.pal(12,'Set3')
brewer.pal(8,'Dark2')
brewer.pal(9,'OrRd')
brewer.pal(9,'RdPu')
brewer.pal(9,'Blues')
brewer.pal(9,'GnBu')
setwd("/Users/xuebozhao/Documents/LuLab/wheatSpeciation/pca/MDS/AB/A")
taxaID = read.table("A_IN_matrix.mdist.id")
info1 = read.delim("/Users/xuebozhao/Documents/LuLab/wheatSpeciation/map/map_file_r.csv",head =T,sep=",")
index = match(taxaID$V1,info1$ID)
meta = info1[index,c(1,7,8,9)]
gen_dist <- read.table("A_IN_matrix.mdist")
gen_null <- sum(unlist(gen_dist))
col_pal <- matrix(rep(brewer.pal(max_k, "Paired"), max_k),nrow=max_k)
glob <- cmdscale(gen_dist, eig=TRUE,k=3)
xl  <- round(glob$eig[1]/sum(glob$eig[which(glob$eig > 0)]),3)*100
yl <- round(glob$eig[2]/sum(glob$eig[which(glob$eig > 0)]),3)*100
##先画一个空的
plot(-glob$points[,2],-glob$points[,1], xlab=yl, ylab=xl, main="Metric MDS", xaxt = 'n', yaxt = 'n', col=  NULL)
index1 = which(meta$Common_name=="Wild emmer")
#points(-glob$points[index1,2],-glob$points[index1,1], col = "#FA9FB5", cex = 1, pch =8)
points(-glob$points[index1,2],-glob$points[index1,1], col = rgb(250/255,159/255,181/255,0.8), cex = 1, pch =8)
index1 = which(meta$Common_name=="Domesticated emmer")
#points(-glob$points[index1,2],-glob$points[index1,1], col = "#BEBADA", cex = 1.5, pch =18)
points(-glob$points[index1,2],-glob$points[index1,1], col = rgb(190/255,186/255,218/255,0.7), cex = 1.7, pch =18)
index1 = which(meta$Common_name=="Ispahanicum")
points(-glob$points[index1,2],-glob$points[index1,1], col = rgb(190/255,186/255,218/255,0.9), cex = 1.2, pch =9)
index1 = which(meta$Common_name=="Georgian wheat")
points(-glob$points[index1,2],-glob$points[index1,1], col = rgb(190/255,186/255,218/255,0.9), cex = 1, pch =3)
index1 = which(meta$Common_name=="Rivet wheat")
points(-glob$points[index1,2],-glob$points[index1,1], col = rgb(179/255,222/255,105/255,0.7), cex = 1.28, pch =17)
index1 = which(meta$Common_name=="Polish wheat")
points(-glob$points[index1,2],-glob$points[index1,1], col = "#B3DE69", cex = 1, pch =11)
index1 = which(meta$Common_name=="Persian wheat")
points(-glob$points[index1,2],-glob$points[index1,1], col = "#B3DE69", cex = 1.2, pch =10)
index1 = which(meta$Common_name=="Khorasan wheat")
points(-glob$points[index1,2],-glob$points[index1,1], col = "#B3DE69", cex = 1, pch =5)
index1 = which(meta$Common_name=="Durum")
points(-glob$points[index1,2],-glob$points[index1,1], col = rgb(179/255,222/255,105/255,0.7), cex = 1.28, pch =15)


index1 = which(meta$Common_name=="Landrace")
#points(-glob$points[index1,2],-glob$points[index1,1], col = "#80B1D3", cex = 1, pch =6)
points(-glob$points[index1,2],-glob$points[index1,1], col = rgb(127/255,177/255,211/255,0.8), cex = 1, pch =6)
index1 = which(meta$Common_name=="Cultivar")
points(-glob$points[index1,2],-glob$points[index1,1], col = rgb(127/255,177/255,211/255,0.8), cex = 1, pch =12)
index1 = which(meta$Common_name=="Spelt")
points(-glob$points[index1,2],-glob$points[index1,1], col = "#80B1D3", cex = 1, pch =0)
index1 = which(meta$Common_name=="Macha")
points(-glob$points[index1,2],-glob$points[index1,1], col = "#80B1D3", cex = 1, pch =7)
index1 = which(meta$Common_name=="Indian_dwarf_wheat")
points(-glob$points[index1,2],-glob$points[index1,1], col = rgb(127/255,177/255,211/255,0.7), cex = 1, pch =16)
index1 = which(meta$Common_name=="Yunan_wheat")
points(-glob$points[index1,2],-glob$points[index1,1], col = "#80B1D3", cex = 1, pch =4)
index1 = which(meta$Common_name=="Tibetan_semi_wild")
points(-glob$points[index1,2],-glob$points[index1,1], col = "#80B1D3", cex = 1, pch =1)
index1 = which(meta$Common_name=="Xinjiang_wheat")
points(-glob$points[index1,2],-glob$points[index1,1], col = "#80B1D3", cex = 1, pch =13)
index1 = which(meta$Common_name=="Vavilovii")
points(-glob$points[index1,2],-glob$points[index1,1], col = "#80B1D3", cex = 1, pch =14)
index1 = which(meta$Common_name=="Club_wheat")
points(-glob$points[index1,2],-glob$points[index1,1], col = "#80B1D3", cex = 1, pch =2)

